config/routes.rb
MixExchange::Application.routes.draw do
  mount Commontator::Engine => '/commontator'

  resources :votes, only: [:show]

  resources :follows, only: [:show, :destroy]

  devise_for :users, :controllers => { :users => "users", :registrations => "registrations" }
  resources :posts

  get 'users/:id' => 'users#show', as: 'user'
  get 'users/:id/feed' => 'users#feed', as: 'feed'

  root 'posts#index'

  

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	before_save :default_values
  def default_values
  	@myimages = ["covers/cover1.jpeg", "covers/cover2.jpeg", "covers/cover3.jpeg", "covers/cover4.jpeg", "covers/cover5.jpeg", "covers/cover6.jpeg"]
    self.post_img ||= @myimages.sample
  end

	belongs_to :user

	acts_as_voteable

	acts_as_commontable

	acts_as_taggable

	mount_uploader :post_img, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts

  acts_as_voter

  acts_as_commontator

  acts_as_followable
  acts_as_follower

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         # ,
         # :confirmable
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, lambda { order("created_at DESC") }

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable if ActiveRecord::VERSION::MAJOR < 4


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:account_update) << :name
	  devise_parameter_sanitizer.for(:account_update) << :profile_pic
	  devise_parameter_sanitizer.for(:sign_up) << :name
	  devise_parameter_sanitizer.for(:sign_up) << :profile_pic
	end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
	before_action :set_user

	def show
		current_user.follow(@user)
		redirect_to user_url(@user.id)
	end

	def destroy
		current_user.stop_following(@user)
		redirect_to user_url(@user.id)
	end

	private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if params[:sort] == 'Top'
      @posts = Post.plusminus_tally.limit(15).order('plusminus_tally DESC')
    elsif params[:sort] == 'New'
      @posts = Post.plusminus_tally.limit(15).order('created_at DESC')
    elsif params[:sort] == 'Hot'
      @posts = Post.plusminus_tally.limit(15).where("posts.created_at >= '#{Time.now-2.days}'").order('plusminus_tally DESC')
    else
      @posts = Post.plusminus_tally.limit(15).where("posts.created_at >= '#{Time.now-2.days}'").order('plusminus_tally DESC')
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.post_img = "covers/cover1"

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :post_img, :embed_url, :tag_list)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
  end

  def feed
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	before_action :set_post

	def show
		current_user.vote_for(@post)
		redirect_to posts_url
	end

	private

	# Callbacks
	def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><a href="#"><%= link_to image_tag('cassette-icon-white.png', :size => '50x50'), posts_path %></a></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="left">
      <li class="divider"></li>
      <li class="active"><a href="#"><%= link_to "My Feed", feed_path(current_user) %></a></li>
      <li class="divider"></li>
      <li class="active"><a href="#"><%= link_to "My Profile", current_user %></a></li>
      <li class="divider"></li>
      <li class="active"><a href="#"><%= link_to 'Create Mixtape', new_post_path%></a></li>
      <li class="divider"></li>
    </ul>
    <ul class="right">
      <li class="divider"></li>
      <% if user_signed_in? %>
        <li class="active"><a href="#"><%= link_to current_user.name, current_user %></a></li>
      <% end %>
      <li class="divider"></li>
      <li class="active"><a href="#"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></a></li>
    </ul>
  </section>
</nav>

<p class="notice center"><%= flash[:notice] %></p>
<p class="alert center"><%= flash[:alert] %></p>

    
    <%= yield %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  %div.row
    %div.small-6.small-centered.columns
      .field
        = f.text_field :title, :placeholder => "Title"
  %div.row
    %div.small-6.small-centered.columns
      .field
        = f.text_area :content, :placeholder => "Content"
  %div.row
    %div.small-6.small-centered.columns
      .field
        = f.text_field :embed_url, :placeholder => "Embed Url"
  %div.row
    %div.small-6.small-centered.columns
      .field
        = f.text_field :tag_list, { :placeholder => "Tags separated by commas" }
  %div.row
    %div.small-6.small-centered.columns
      %h3 Cover Art
      .field
        = f.file_field :post_img, :class => 'button'
  %div.row
    %div.small-6.small-centered.columns
      .actions.center
        = f.submit 'Save', :class => 'button'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1
  = params[:sort]
  mixtapes

%div.center
  %a.small.button.dropdown{"data-dropdown" => "drop1", :href => "#"} sort

%br
  %ul#drop1.f-dropdown
    %li
      %a= link_to 'Top', posts_path(:sort => 'Top')
    %li
      %a= link_to 'New', posts_path(:sort => 'New')
    %li
      %a= link_to 'Hot', posts_path(:sort => 'Hot')

%div.row
  - @posts.each do |post|
    %div.small-12.large-4.columns.container
      - if post.post_img?
        %div.image= image_tag post.post_img_url
      - else
        %div.image= image_tag 'http://placehold.it/500x500'
      %div.inside-container
        %div.title
          = link_to post.title, post
        %div.author
          by,
          = link_to post.user.name, user_url(post.user_id)
        %div.count
          = post.votes.count
        %div.upvote
          = link_to image_tag('up_arrow.png', :size => '30x30'), vote_path(post), method: :get

app/views/posts/new.html.haml
%h1 New post

= render 'form'

app/views/posts/show.html.haml
%p#notice= notice

%h1.large= @post.title
%p.center 
	Author: 
	= link_to @post.user.name, user_url(@post.user_id)
- if current_user == @post.user
	%p.center
		= link_to 'Edit', edit_post_path(@post)
		\|
		= link_to 'Destroy', post_path(@post), :method => :delete, :data => { :confirm => 'Are you sure?' }
		\|
		= link_to 'Back', posts_path
%p.center
	= raw @post.embed_url
%p.center
	Tags:
	- @post.tag_list.each do |x|
		= x
%div.row
	%p.columns.large-6= image_tag @post.post_img
	%p.columns.large-6= @post.content
		
= commontator_thread(@post)

app/views/users/feed.html.haml
%h3
	= @user.name 
	Feed

- if current_user == @user
	%h3
		Following:
		= current_user.follow_count
		Users
	%div.row
		- current_user.following_users.includes(:posts).collect{|u| u.posts}.flatten.each do |post|
			%div.small-12.large-4.columns.container
				- if post.post_img?
					%div.image= image_tag post.post_img_url
				- else
					%div.image= image_tag 'http://placehold.it/500x500'
				%div.inside-container
					%div.view.title
						= link_to post.title, post
					%div.view.author
						by,
						= link_to post.user.name, user_url(post.user_id)
					%div.view.count
						= post.votes.count
					%div.view.upvote
						= link_to image_tag('up_arrow.png', :size => '30x30'), vote_path(post), method: :get

app/views/users/show.html.haml
%h3
	= @user.name 
	Posts

- if current_user.following?(@user)
	%p.center You are following this user!

- if current_user == @user
- else
	%p.center
		= link_to "Follow", follow_path(@user), method: :get
		= link_to "Unfollow", follow_path(@user), method: :delete

%div.row
	- @user.posts.each do |post|
		%div.small-12.large-4.columns.container
			- if post.post_img?
				%div.image= image_tag post.post_img_url
			- else
				%div.image= image_tag 'http://placehold.it/500x500'
			%div.inside-container
				%div.view.title
					= link_to post.title, post
				%div.view.author
					by,
					= link_to post.user.name, user_url(post.user_id)
				%div.view.count
					= post.votes.count
				%div.view.upvote
					= link_to image_tag('up_arrow.png', :size => '30x30'), vote_path(post), method: :get